---
#
# Ansible managed
#
dependency:
  name: galaxy
lint: |
  yamllint molecule/default/converge.yml
  ansible-lint molecule/default/converge.yml
driver:
  name: docker
provisioner:
  name: ansible
  lint: 
    name: ansible-lint
verifier:
  name: ansible
