---
name: CI
on:
  push:
    branches:
    - master
    - release/*
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.3.4
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - image: debian
            tag: jessie
          - image: debian
            tag: buster
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.3.4
        with:
          image: "${{ matrix.image }}"
          tag: "${{ matrix.tag }}"
          options: "--parallel all"
